### ISSUE TITLE
关于《REACT HOOKS与SETINTERVAL》的提问

### ISSUE THREAD

**Issue by andyyxw** [raoenhui/raoenhui.github.io#39]
<img width="405" alt="Snipaste_2020-04-28_20-59-59" src="https://user-images.githubusercontent.com/41931722/80490185-90289d00-8993-11ea-8b70-53fd1010a358.png">
这里使用`let`与`const`有区别吗，是刻意的吗？

**Comment by andyyxw** [comment]
<img width="531" alt="Snipaste_2020-04-28_21-00-27" src="https://user-images.githubusercontent.com/41931722/80490341-cbc36700-8993-11ea-8fbc-42df99b137bc.png">
为什么`useEffect`中没有`clearInterval`呢？

**Comment by raoenhui** [comment]
> <img alt="Snipaste_2020-04-28_20-59-59" width="405" src="https://user-images.githubusercontent.com/41931722/80490185-90289d00-8993-11ea-8b70-53fd1010a358.png">
> 
> 这里使用`let`与`const`有区别吗，是刻意的吗？

不是刻意的，可以用`const`的

**Comment by raoenhui** [comment]
> <img alt="Snipaste_2020-04-28_21-00-27" width="531" src="https://user-images.githubusercontent.com/41931722/80490341-cbc36700-8993-11ea-8fbc-42df99b137bc.png">
> 
> 为什么`useEffect`中没有`clearInterval`呢？

这里是需要加`clearInterval`

**Comment by raoenhui** [comment]
谢谢你的问题，以上已更新到[blog](https://raoenhui.github.io/react/2019/11/07/hooksSetinterval/index.html),期待新的问题
